### create admin
POST http://localhost:3000/users
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Leo",
    "email": "leo@user.com",
    "password": "aaaa",
    "role": "WRITER"
}

###
### create reader
POST http://localhost:3000/users
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "read",
    "email": "read@user.com",
    "password": "aaaa",
    "role": "READER"
}

###

###
# @name readLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "read@user.com",
    "password": "aaaa"
}

###
@readToken = {{readLogin.response.body.access_token}}

###

GET http://localhost:3000/users
Authorization: Bearer {{tokenLeo}}

###

GET http://localhost:3000/users/f5b53f07-34db-4151-a79d-8f4bd0411786
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imxlb0B1c2VyLmNvbSIsIm5hbWUiOiJMZW8iLCJpYXQiOjE3NDM2NDMyMjAsImV4cCI6MTc0MzY1MDQyMH0.DFhTtHgXxwFdB-vgwFMIOe4QhPhi1CfXPngpgjs4vtc

###
# @name adminLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@user.com",
    "password": "admin"
}

###
@adminToken = {{adminLogin.response.body.access_token}}

###

POST http://localhost:3000/posts
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "title": "Post 1",
    "content": "Content one",
    "published": true
}


###
# @name LeoLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "leo@user.com",
    "password": "aaaa"
}

###
@tokenLeo = {{LeoLogin.response.body.access_token}}

###

POST http://localhost:3000/posts
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "title": "Post 20",
    "content": "Content two",
    "published": false
}

###

GET http://localhost:3000/posts
Authorization: Bearer {{adminToken}}

###
GET http://localhost:3000/posts/f5b53f07-34db-4151-a79d-8f4bd0411786
Authorization: Bearer {{readToken}}
