### login as admin
# @name adminLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@user.com",
    "password": "admin"
}

###
@adminToken = {{adminLogin.response.body.access_token}}

### create reader
POST http://localhost:3000/users
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Reader3",
    "email": "reader3@user.com",
    "password": "aaaa",
    "role": "READER"
}

### login as reader
# @name readerLogin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "reader3@user.com",
    "password": "aaaa"
}

###
@readerToken = {{readerLogin.response.body.access_token}}

### get posts
GET http://localhost:3000/posts
Authorization: Bearer {{readerToken}}


### create post
POST http://localhost:3000/posts
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "title": "Post 1",
    "content": "Content one",
    "published": true
}

### create user as reader
POST http://localhost:3000/users
Authorization: Bearer {{readerToken}}
Content-Type: application/json

{
    "name": "testeee",
    "email": "leo222@user.com",
    "password": "aaaa",
    "role": "WRITER"
}

###