POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Leo",
    "email": "leo@user.com",
    "password": "aaaa",
    "role": "WRITER"
}

###

GET http://localhost:3000/users

###

GET http://localhost:3000/users/46897654-8d10-435d-8460-52aed625c11f
